networks:
  visualgo-network:
    driver: bridge
services:
  frontend:
    image: node:current-alpine3.22
    command: sh -c "yarn && yarn dev"
    ports:
      - 5173:5173
    working_dir: /frontend
    environment:
      VITE_BACKEND_HOST: backend
      VITE_BACKEND_PORT: 8000


    volumes:
      - ./frontend:/frontend
    depends_on:
      - backend
    networks:
      - visualgo-network
  backend:
    image: node:current-alpine3.22
    command: sh -c "yarn && yarn dev"
    ports:
      - 8000:8000
    environment:
      PORT: 8000
      DB_DATABASE: "test"
      DB_HOST: "postgres-db"
      DB_USERNAME: "postgres"
      DB_PORT: 5432,
      DB_PASSWORD: "test"
      SECRET: "SECRET"
    working_dir: /backend
    volumes:
        - ./backend:/backend
    networks:
      - visualgo-network
    depends_on:
      - postgres-db
  # valkey:
  #   build: /valkey
  #   command: sh -c "redis-server redis.conf"
  #   ports:
  #     - 6379:6379
  #   networks:
  #     - visualgo-network
  postgres-db:
    image: postgres:latest
    shm_size: 256mb
    environment:
      POSTGRES_PASSWORD: test
    ports:
      - 5432:5432
    networks:
      - visualgo-network
    volumes:
      - ./postgres:/var/lib/postgresql
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
