/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ViewerRouteImport } from './routes/viewer'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserUsernameRouteImport } from './routes/user.$username'
import { Route as PostPostidRouteImport } from './routes/post.$postid'

const ViewerRoute = ViewerRouteImport.update({
  id: '/viewer',
  path: '/viewer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserUsernameRoute = UserUsernameRouteImport.update({
  id: '/user/$username',
  path: '/user/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const PostPostidRoute = PostPostidRouteImport.update({
  id: '/post/$postid',
  path: '/post/$postid',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/viewer': typeof ViewerRoute
  '/post/$postid': typeof PostPostidRoute
  '/user/$username': typeof UserUsernameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/viewer': typeof ViewerRoute
  '/post/$postid': typeof PostPostidRoute
  '/user/$username': typeof UserUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/viewer': typeof ViewerRoute
  '/post/$postid': typeof PostPostidRoute
  '/user/$username': typeof UserUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/viewer' | '/post/$postid' | '/user/$username'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/viewer' | '/post/$postid' | '/user/$username'
  id: '__root__' | '/' | '/viewer' | '/post/$postid' | '/user/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ViewerRoute: typeof ViewerRoute
  PostPostidRoute: typeof PostPostidRoute
  UserUsernameRoute: typeof UserUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/viewer': {
      id: '/viewer'
      path: '/viewer'
      fullPath: '/viewer'
      preLoaderRoute: typeof ViewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$username': {
      id: '/user/$username'
      path: '/user/$username'
      fullPath: '/user/$username'
      preLoaderRoute: typeof UserUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$postid': {
      id: '/post/$postid'
      path: '/post/$postid'
      fullPath: '/post/$postid'
      preLoaderRoute: typeof PostPostidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ViewerRoute: ViewerRoute,
  PostPostidRoute: PostPostidRoute,
  UserUsernameRoute: UserUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
